# Generated by Django 3.2.16 on 2023-01-19 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0005_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traveler', models.CharField(max_length=80)),
                ('share_body', models.TextField(max_length=1000)),
                ('share_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='social_app.story')),
            ],
        ),
    ]
