# Generated by Django 3.2.16 on 2023-04-30 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0009_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ShareUserStory',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
